### PR TITLE
Added Github Workflow support for Docker buildkit, using the same tagging as before (ref tagging) but with the Docker metadata action and build v3.

### PR DESCRIPTION
**Pull request by lucasantarella**

### CODE REVIEW

**Comment by lucasantarella** [comment]
@muonsoft Thanks for a great repo! I updated the Github actions file to include some updates to the Docker build so that builds use buildkit and incorporate the multi-platform builds that are available with the new version.

This will allow native running on those with M1 chips and Docker.

Let me know if I can help with anything else!

**Comment by strider2038** [comment]
@lucasantarella thanks for PR!

**Comment by strider2038** [comment]
Docker build fails https://github.com/muonsoft/openapi-mock/actions/runs/3399182915/jobs/5652768931

```
ERROR: multiple platforms feature is currently not supported for docker driver. Please switch to a different driver (eg. "docker buildx create --use")
Error: buildx failed with: ERROR: multiple platforms feature is currently not supported for docker driver. Please switch to a different driver (eg. "docker buildx create --use")
```

@lucasantarella can you help to fix this?

**Comment by smoench** [comment]
> Docker build fails https://github.com/muonsoft/openapi-mock/actions/runs/3399182915/jobs/5652768931
> 
> ```
> ERROR: multiple platforms feature is currently not supported for docker driver. Please switch to a different driver (eg. "docker buildx create --use")
> Error: buildx failed with: ERROR: multiple platforms feature is currently not supported for docker driver. Please switch to a different driver (eg. "docker buildx create --use")
> ```
> 
> @lucasantarella can you help to fix this?

I provided a fix in this [PR](https://github.com/muonsoft/openapi-mock/pull/80) :-)

**Pull request merged**
